name: Testing
language: python
os:
  - linux
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install requests
before_script: cd src
script: python3 -m unittest discover
services: mongodb
