name: Flask App CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install pymongo
          pip install flask_pymongo
          pip install flask_mail
          pip install flask_wtf
          pip install wtforms
          pip install pytz
          pip install itsdangerous
          pip install werkzeug
          pip install schedule
          pip install apscheduler
          pip install tabulate
          pip install bcrypt
          pip install requests
          pip install openai
          pip install pytest
          pip install pytest-flask

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run Tests
        env:
          MONGO_URI: mongodb://localhost:27017/simplii_test
        run: pytest test_application.py --maxfail=1 --disable-warnings
