name: Flask App CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: "--health-cmd='echo db.runCommand({ ping: 1 }) | mongo localhost:27017/test --quiet' --health-interval=10s --health-timeout=5s --health-retries=5"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pymongo

      - name: Run Tests
        env:
          MONGO_URI: mongodb://localhost:27017/simplii
        run: pytest test_application.py --maxfail=1 --disable-warnings
