name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies manually
      run: |
        python -m pip install --upgrade pip
        pip install Flask
        pip install Flask-WTF
        pip install Flask-PyMongo
        pip install Flask-Mail
        pip install Werkzeug
        pip install pymongo
        pip install tabulate
        pip install apscheduler
        pip install pytz
        pip install bcrypt
        pip install openai
        pip install requests
        pip install schedule
        pip install itsdangerous
        pip install wtforms
        pip uninstall -y bson  # Ensure no conflict with pymongo's bson

    - name: Run tests
      run: |
        python -m unittest discover -s src -p "test_*.py"
